#!/bin/sh
### BEGIN INIT INFO
# Provides:          sshd
# Required-Start:    $network
# Default-Start:     S
# Short-Description: Start OpenSSH server
### END INIT INFO

case "$1" in
    start)
        echo "Starting sshd..."
        /usr/sbin/sshd
        ;;
    stop)
        echo "Stopping sshd..."
        killall sshd
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
exit 0
