#!/bin/sh
### BEGIN INIT INFO
# Provides:          mosquitto
# Required-Start:    $network
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      
# Short-Description: Start Mosquitto MQTT broker
### END INIT INFO

case "$1" in
  start)
    echo "Starting Mosquitto..."
    /usr/sbin/mosquitto -d
    ;;
  stop)
    echo "Stopping Mosquitto..."
    killall mosquitto
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit 0
